### ISSUE TITLE
Questions about estimate_oc

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/BlueCarbon#26]
Opening this thread to resolve some questions:

1. What units are used for organic carbon and organic matter?

**Comment by Pakillo** [comment]
I'm unsure about using

1. lm(OC ~ OM)
2. lm(log(OC) ~ log(OM))
3. glm with lognormal distribution

thoughts?

**Comment by NPJuncal** [comment]
Hi!
organic carbon and organic matter are in %. The final result will depend in the units of the dry bulk density (dbd). The example dataset dbd is in g/cm3, therefore the stock will be g/cm2 by standar depth (by default g/cm2 by one meter). The dbd units are not important, but it is cumpulsory that organic matter and organic carbon are provided in %, because of how the calculations are done to estimate g of C per cm3. I should add that into the codumentation of the function, and maybe a warning?

**Comment by Pakillo** [comment]
ok thanks! Noted, OM and OC in %

For the models, let's keep lm(log) by now, pending further checks
